# Generated by Django 4.2.6 on 2023-11-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='p_phone',
        ),
    ]
