# Generated by Django 4.2.6 on 2023-11-21 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_booking_p_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='p_phone',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
