# Generated by Django 4.2.6 on 2023-11-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_booking_p_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='p_phone',
            field=models.CharField(max_length=10),
        ),
    ]
